//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeBooks.Resource {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FreeBooks.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string lbActionName {
            get {
                return ResourceManager.GetString("lbActionName", resourceCulture);
            }
        }
        
        internal static string lbActiveUser {
            get {
                return ResourceManager.GetString("lbActiveUser", resourceCulture);
            }
        }
        
        internal static string lbAddNewCategory {
            get {
                return ResourceManager.GetString("lbAddNewCategory", resourceCulture);
            }
        }
        
        internal static string lbAddNewRole {
            get {
                return ResourceManager.GetString("lbAddNewRole", resourceCulture);
            }
        }
        
        internal static string lbbtnChangePassword {
            get {
                return ResourceManager.GetString("lbbtnChangePassword", resourceCulture);
            }
        }
        
        internal static string lbbtnDelete {
            get {
                return ResourceManager.GetString("lbbtnDelete", resourceCulture);
            }
        }
        
        internal static string lbbtnEdit {
            get {
                return ResourceManager.GetString("lbbtnEdit", resourceCulture);
            }
        }
        
        internal static string lbbtnPermissions {
            get {
                return ResourceManager.GetString("lbbtnPermissions", resourceCulture);
            }
        }
        
        internal static string lbbtnSave {
            get {
                return ResourceManager.GetString("lbbtnSave", resourceCulture);
            }
        }
        
        internal static string lbbtnSaveNewCategory {
            get {
                return ResourceManager.GetString("lbbtnSaveNewCategory", resourceCulture);
            }
        }
        
        internal static string lbbtnSaveNewRole {
            get {
                return ResourceManager.GetString("lbbtnSaveNewRole", resourceCulture);
            }
        }
        
        internal static string lbbtnSaveNewUser {
            get {
                return ResourceManager.GetString("lbbtnSaveNewUser", resourceCulture);
            }
        }
        
        internal static string lbcancelButtonText {
            get {
                return ResourceManager.GetString("lbcancelButtonText", resourceCulture);
            }
        }
        
        internal static string lbCategories {
            get {
                return ResourceManager.GetString("lbCategories", resourceCulture);
            }
        }
        
        internal static string lbComparePassword {
            get {
                return ResourceManager.GetString("lbComparePassword", resourceCulture);
            }
        }
        
        internal static string lbconfirmButtonText {
            get {
                return ResourceManager.GetString("lbconfirmButtonText", resourceCulture);
            }
        }
        
        internal static string lbDate {
            get {
                return ResourceManager.GetString("lbDate", resourceCulture);
            }
        }
        
        internal static string lbDescription {
            get {
                return ResourceManager.GetString("lbDescription", resourceCulture);
            }
        }
        
        internal static string lbEdit {
            get {
                return ResourceManager.GetString("lbEdit", resourceCulture);
            }
        }
        
        internal static string lbEmailUser {
            get {
                return ResourceManager.GetString("lbEmailUser", resourceCulture);
            }
        }
        
        internal static string lbEvents {
            get {
                return ResourceManager.GetString("lbEvents", resourceCulture);
            }
        }
        
        internal static string lbHomePage {
            get {
                return ResourceManager.GetString("lbHomePage", resourceCulture);
            }
        }
        
        internal static string lbImageUser {
            get {
                return ResourceManager.GetString("lbImageUser", resourceCulture);
            }
        }
        
        internal static string lbLogCategories {
            get {
                return ResourceManager.GetString("lbLogCategories", resourceCulture);
            }
        }
        
        internal static string lbManageBook {
            get {
                return ResourceManager.GetString("lbManageBook", resourceCulture);
            }
        }
        
        internal static string lbManagePermission {
            get {
                return ResourceManager.GetString("lbManagePermission", resourceCulture);
            }
        }
        
        internal static string lbMsgDeletedOkCategory {
            get {
                return ResourceManager.GetString("lbMsgDeletedOkCategory", resourceCulture);
            }
        }
        
        internal static string lbMsgDeletedOkRegister {
            get {
                return ResourceManager.GetString("lbMsgDeletedOkRegister", resourceCulture);
            }
        }
        
        internal static string lbMsgDeletedOkRole {
            get {
                return ResourceManager.GetString("lbMsgDeletedOkRole", resourceCulture);
            }
        }
        
        internal static string lbMsgDenied {
            get {
                return ResourceManager.GetString("lbMsgDenied", resourceCulture);
            }
        }
        
        internal static string lbMsgDuplicateNameCategory {
            get {
                return ResourceManager.GetString("lbMsgDuplicateNameCategory", resourceCulture);
            }
        }
        
        internal static string lbMsgErrorLogin {
            get {
                return ResourceManager.GetString("lbMsgErrorLogin", resourceCulture);
            }
        }
        
        internal static string lbMsgNotSavedCategory {
            get {
                return ResourceManager.GetString("lbMsgNotSavedCategory", resourceCulture);
            }
        }
        
        internal static string lbMsgNotSavedChangePassword {
            get {
                return ResourceManager.GetString("lbMsgNotSavedChangePassword", resourceCulture);
            }
        }
        
        internal static string lbMsgNotUpdatedCategory {
            get {
                return ResourceManager.GetString("lbMsgNotUpdatedCategory", resourceCulture);
            }
        }
        
        internal static string lbMsgSaveCategory {
            get {
                return ResourceManager.GetString("lbMsgSaveCategory", resourceCulture);
            }
        }
        
        internal static string lbMsgSavedChangePassword {
            get {
                return ResourceManager.GetString("lbMsgSavedChangePassword", resourceCulture);
            }
        }
        
        internal static string lbMsgUpdateCategory {
            get {
                return ResourceManager.GetString("lbMsgUpdateCategory", resourceCulture);
            }
        }
        
        internal static string lbNameCategory {
            get {
                return ResourceManager.GetString("lbNameCategory", resourceCulture);
            }
        }
        
        internal static string lbNameRole {
            get {
                return ResourceManager.GetString("lbNameRole", resourceCulture);
            }
        }
        
        internal static string lbNameUser {
            get {
                return ResourceManager.GetString("lbNameUser", resourceCulture);
            }
        }
        
        internal static string lbNotSaved {
            get {
                return ResourceManager.GetString("lbNotSaved", resourceCulture);
            }
        }
        
        internal static string lbNotSavedMsgRole {
            get {
                return ResourceManager.GetString("lbNotSavedMsgRole", resourceCulture);
            }
        }
        
        internal static string lbNotSavedMsgUser {
            get {
                return ResourceManager.GetString("lbNotSavedMsgUser", resourceCulture);
            }
        }
        
        internal static string lbNotSavedMsgUserRole {
            get {
                return ResourceManager.GetString("lbNotSavedMsgUserRole", resourceCulture);
            }
        }
        
        internal static string lbNotUpdate {
            get {
                return ResourceManager.GetString("lbNotUpdate", resourceCulture);
            }
        }
        
        internal static string lbNotUpdateMsgRole {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgRole", resourceCulture);
            }
        }
        
        internal static string lbNotUpdateMsgUser {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgUser", resourceCulture);
            }
        }
        
        internal static string lbNotUpdateMsgUserRole {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgUserRole", resourceCulture);
            }
        }
        
        internal static string lbOk {
            get {
                return ResourceManager.GetString("lbOk", resourceCulture);
            }
        }
        
        internal static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        internal static string lbRegisters {
            get {
                return ResourceManager.GetString("lbRegisters", resourceCulture);
            }
        }
        
        internal static string lbRoles {
            get {
                return ResourceManager.GetString("lbRoles", resourceCulture);
            }
        }
        
        internal static string lbRoleUser {
            get {
                return ResourceManager.GetString("lbRoleUser", resourceCulture);
            }
        }
        
        internal static string lbSave {
            get {
                return ResourceManager.GetString("lbSave", resourceCulture);
            }
        }
        
        internal static string lbSaveMsgRole {
            get {
                return ResourceManager.GetString("lbSaveMsgRole", resourceCulture);
            }
        }
        
        internal static string lbSaveMsgUser {
            get {
                return ResourceManager.GetString("lbSaveMsgUser", resourceCulture);
            }
        }
        
        internal static string lbSelectUserRole {
            get {
                return ResourceManager.GetString("lbSelectUserRole", resourceCulture);
            }
        }
        
        internal static string lbTextMsgDelete {
            get {
                return ResourceManager.GetString("lbTextMsgDelete", resourceCulture);
            }
        }
        
        internal static string lbTitleDeletedOk {
            get {
                return ResourceManager.GetString("lbTitleDeletedOk", resourceCulture);
            }
        }
        
        internal static string lbTitleEdit {
            get {
                return ResourceManager.GetString("lbTitleEdit", resourceCulture);
            }
        }
        
        internal static string lbTitleEditCategory {
            get {
                return ResourceManager.GetString("lbTitleEditCategory", resourceCulture);
            }
        }
        
        internal static string lbTitleMsgDelete {
            get {
                return ResourceManager.GetString("lbTitleMsgDelete", resourceCulture);
            }
        }
        
        internal static string lbUpdate {
            get {
                return ResourceManager.GetString("lbUpdate", resourceCulture);
            }
        }
        
        internal static string lbUpdateMsgRole {
            get {
                return ResourceManager.GetString("lbUpdateMsgRole", resourceCulture);
            }
        }
        
        internal static string lbUpdateMsgUser {
            get {
                return ResourceManager.GetString("lbUpdateMsgUser", resourceCulture);
            }
        }
        
        internal static string lbUser {
            get {
                return ResourceManager.GetString("lbUser", resourceCulture);
            }
        }
        
        internal static string lbUserName {
            get {
                return ResourceManager.GetString("lbUserName", resourceCulture);
            }
        }
        
        internal static string lbLogout {
            get {
                return ResourceManager.GetString("lbLogout", resourceCulture);
            }
        }
    }
}
